FROM openjdk:11.0
LABEL maintainer "lonisy <lonisy@163.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux"

ENV APP_NAME="kafka" \
    IMAGE_VERSION="kafka_2.11-0.10.1.1" \
    PATH="/kafka_2.11-0.10.1.1/bin:$PATH"

COPY kafka_2.11-0.10.1.1 /kafka_2.11-0.10.1.1


